# Generated by Django 4.2.3 on 2023-07-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callback',
            old_name='email',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='callback',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='location',
        ),
    ]
